name: linting

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.5'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

        run: |
            curl -OL https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
            tar xf shellcheck-stable.linux.x86_64.tar.xz
            sudo mv shellcheck-stable/shellcheck /usr/local/bin

            pip3 install poetry
            poetry install

            true; PYTHONPATH=. bash ./tasks/lint.sh