name: linting

on: [push]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7.5]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
      - name: View poetry --help
        run: poetry --help
      - name: dependency installation
        run: sudo poetry install
          
      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

        run: |
            curl -OL https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
            tar xf shellcheck-stable.linux.x86_64.tar.xz
            sudo mv shellcheck-stable/shellcheck /usr/local/bin
